//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConverter.CurrencyConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyConverterService.IConverterService")]
    public interface IConverterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ReplaceCommaBypoint", ReplyAction="http://tempuri.org/IConverterService/ReplaceCommaBypointResponse")]
        string ReplaceCommaBypoint(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/ReplaceCommaBypoint", ReplyAction="http://tempuri.org/IConverterService/ReplaceCommaBypointResponse")]
        System.Threading.Tasks.Task<string> ReplaceCommaBypointAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/CurrencyInWord", ReplyAction="http://tempuri.org/IConverterService/CurrencyInWordResponse")]
        string CurrencyInWord(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConverterService/CurrencyInWord", ReplyAction="http://tempuri.org/IConverterService/CurrencyInWordResponse")]
        System.Threading.Tasks.Task<string> CurrencyInWordAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConverterServiceChannel : CurrencyConverter.CurrencyConverterService.IConverterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConverterServiceClient : System.ServiceModel.ClientBase<CurrencyConverter.CurrencyConverterService.IConverterService>, CurrencyConverter.CurrencyConverterService.IConverterService {
        
        public ConverterServiceClient() {
        }
        
        public ConverterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ReplaceCommaBypoint(string value) {
            return base.Channel.ReplaceCommaBypoint(value);
        }
        
        public System.Threading.Tasks.Task<string> ReplaceCommaBypointAsync(string value) {
            return base.Channel.ReplaceCommaBypointAsync(value);
        }
        
        public string CurrencyInWord(string value) {
            return base.Channel.CurrencyInWord(value);
        }
        
        public System.Threading.Tasks.Task<string> CurrencyInWordAsync(string value) {
            return base.Channel.CurrencyInWordAsync(value);
        }
    }
}
